name: Deploy Application

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      stage:
        type: choice
        default: "dev"
        description: select the env
        options:
          - "dev"
          - "stage"

      aws_region:
        type: choice
        default: "ap-south-1"
        description: aws region name
        options:
          - "ap-south-1"
          - "ap-southeast-1"

env:
  STAGE: "abcd"
  AWS_REGION: "test"

# set this to your preferred AWS region, e.g. ap-south-1

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    env:
      STAGE: ${{ github.event.inputs.stage }}
      AWS_REGION: ${{ github.event.inputs.aws_region }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: print env variable
        run: |
          echo ${{ env.AWS_REGION }}
          echo ${{ env.STAGE }}

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   if: ${{ github.event_name == 'push' }}
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.AWS_REGION }}

      # - name: Set up Python 3.9
      #   uses: actions/setup-python@v3
      #   with:
      #     python-version: "3.9"
      # - name: Install dependencies
      #   run: |
      #     python -m pip install chalice

      # - name: Chalice deploy
      #   run: chalice deploy --stage ${{ env.STAGE }}
