name: Deploy Application

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      stage:
        type: choice
        default: "dev"
        description: select the env
        options:
          - "dev"
          - "stage"

      aws_region:
        type: choice
        default: "ap-south-1"
        description: aws region name
        options:
          - "ap-south-1"
          - "ap-southeast-1"

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    env:
      STAGE: "stage"
      AWS_REGION: "ap-south-1"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        if: ${{ github.event_name == 'push' }}
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install chalice

      - name: Chalice deploy
        #run: chalice deploy --stage ${{ env.STAGE }}
        run: echo ${{ env.STAGE }}

  manual-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' }}

    env:
      STAGE: ${{ github.event.inputs.stage }}
      AWS_REGION: ${{ github.event.inputs.aws_region }} # set this to your preferred AWS region, e.g. ap-south-1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        if: ${{ github.event_name == 'push' }}
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python -m pip install chalice
          
      - name: Deployment Triggered Notification
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "text": "Deployment Triggered on env: ${{ env.STAGE }} :rocket:"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Chalice deploy
        #run: chalice deploy --stage ${{ env.STAGE }}
        run: ech ${{ env.STAGE }}
        
      - name: Deployment Success Notification
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "text": "Deployed Successfully on env: ${{ env.STAGE }} :white_check_mark:"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Deployment Failure Notification
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.19.0
        with:
          payload: |
            {
              "text": "Deployment Failed on env: ${{ env.STAGE }} :x:"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
