name: Deploy Application

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      stage:
        description: select the env
        required: true
        default: "dev"

      aws_region:
        description: aws region name
        required: true
        default: "ap-south-1"

env:
  STAGE: ${{ github.event.inputs.stage }}
  AWS_REGION: ${{ github.event.inputs.aws_region }} # set this to your preferred AWS region, e.g. ap-south-1

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: print env variables
        run: |
          echo ${{ env.STAGE }}
          echo ${{ env.AWS_REGION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install chalice

      - name: Chalice deploy
        run: chalice deploy --stage ${{ env.STAGE }}
